### ISSUE TITLE
Viewing Saved Searches in Inline Edit Mode Freezes Chrome

### ISSUE THREAD

**Issue by czdz** [burkybang/SuiteAdvanced-Feedback#82] opened 2023-04-23 10:05 UTC
Whenever I view a list, Chrome freezes for 10 to 15 seconds. Nothing can be clicked. Tab bar says Chrome is not responding. In the bottom right, NetSuite's yellow Offline flag eventually appears. This happens across all open browser windows across 5 monitors simultaneously. And then the browser snaps back to life. It always recovers, never crashes.

Disabling SuiteAdvanced resolves the problem. Have been a paid user for several months and I do recall a time when this wasn't an issue. It has been going on for sometime now. Can't say how long, however.

I do have a number of extensions including many of the free netSuite addons. I did not try to disable any other addons as that's not practical. If there are any extensions that you know are not compatible with SA please advise. Otherwise, please help resolve. This issue is getting tiresome.

Running latest Chrome and on NS 2023.1 (issue started with 2022.2). Running SA v26.7.0.

Best wishes and appreciate your attention to this matter.

**Comment by burkybang** [comment] 2023-04-26 12:24
I've been thinking about what this could be. 🤔

It sort of sounds familiar. I experienced a similar issue for a while. I didn't see NetSuite's yellow offline flag, however. For me, it only happened when logging into a NetSuite account. I could not figure out the cause of the freezing. It just went away one day after a Chrome update.

Your issue sounds similar, but not exactly the same.

You could try enabling SuiteAdvanced to run in incognito mode. Then try using NetSuite via incognito mode (assuming you don't have any other extensions also enabled in incognito mode) and see if the issue still occurs.

**Comment by burkybang** [comment] 2023-04-30 18:10
Closing since I haven't heard form you. Hoping you got something figure out

**Comment by czdz** [comment] 2023-04-30 20:30
I thought I'd get a better solution than this. Tried it. didn't happen. now
what?



toynk accounting | accountingTeam

***@***.*** ***@***.***>* | Toynk Toys, LLC

<http://www.toynk.com/>

**Comment by burkybang** [comment] 2023-04-30 21:05
It's not an issue that I can reproduce, so it's difficult to know what's causing it. I'd be happy to schedule a screen share meeting with you, so you can demonstrate the issue, and I can better understand what's going on. If you'd like to do that, please email me at support@burkybang.com.

**Comment by burkybang** [comment] 2023-05-04 18:24
@czdz Thanks for your email. I replied with a link that lets you schedule a meeting with me.

**Comment by burkybang** [comment] 2023-06-22 20:07
@czdz I have not heard from you in almost 2 months. I'm closing this issue. Feel free reply whenever, and I can reopen it.

**Closed by burkybang** 2023-06-22 20:07 UTC

**Comment by czdz** [comment] 2023-06-23 06:40
The issue persists. I just have no time to deal with it. if my schedule
ever lightens I'll reach out. this is a very annoying situation


toynk accounting | accountingTeam

***@***.*** ***@***.***>* | Toynk Toys, LLC

<http://www.toynk.com/>

**Comment by burkybang** [comment] 2023-06-23 12:59
You’re welcome to disable SuiteAdvanced or cancel your subscription if it's too annoying.

**Comment by czdz** [comment] 2023-06-23 14:45
Hopefully it doesn't come to that.


toynk accounting | accountingTeam

***@***.*** ***@***.***>* | Toynk Toys, LLC

<http://www.toynk.com/>
