### ISSUE TITLE
View button on Partner page does nothing

### ISSUE THREAD

**Issue by srisoff** [burkybang/SuiteAdvanced-Feedback#28] opened 2022-05-12 13:53 UTC
**Describe the bug**
_A clear and concise description of what the bug is._

Answer: When on the partner page, clicking the View button does not do anything

___

**How to reproduce**
_Describe steps to reproduce the behavior. Example:_
1. _Go to *URL*_
2. _Click on...._
3. _Scroll down to...._
4. _See error_

Answer: Go to a partner record. Click edit. Wait for page to load. Click the view button.

___

**Expected behavior**
_A clear and concise description of what you expected to happen._

Answer: Expect to reload the page in view mode.

___

**Screenshots**
_If applicable, add screenshots to help explain your problem._

Answer: 
![image](https://user-images.githubusercontent.com/33101549/168091304-024ca707-6140-4a92-8643-c35c9aa74321.png)

___

**Additional context**
_Add any other context about the problem here._

Answer:

**Comment by burkybang** [comment] 2022-05-12 15:22
I'm not able to reproduce this issue 🤔

**Comment by srisoff** [comment] 2022-05-12 15:27
Hmm. Well it works in one account but I am still unable to make it do something in the account I first noticed it in.

Best regards,

Scott Risoff
Senior ERP Consultant

***@***.***
Direct:  319.739.2941
Fax:  319.294.9003
www.bergankdv.com<http://www.bergankdv.com/>
www.linkedin.com/in/scott-risoff<http://www.linkedin.com/in/scott-risoff>

CONNECT WITH US
[linkedin]<https://www.linkedin.com/company/bergankdv>  [twitter] <https://twitter.com/BerganKDV>   [facebook] <https://www.facebook.com/BerganKDV>   [instagram] <https://instagram.com/bergankdv/>   [youtube] <https://www.youtube.com/channel/UCuA7FKd4TNJ4XqXhikC39Fg>

[O-NetSuite-Cert-SuiteFoundation-horz-rgb]
[MCTS_2013(rgb)_1309]

________________________________
***Caution: this email came from an external source. Please think before clicking on any links or attachments.***

**Comment by burkybang** [comment] 2022-05-12 15:28
Can you open the browser console before clicking the button? Then click the button, and see if anything displays. If so, send it here.

**Comment by srisoff** [comment] 2022-05-12 15:31
I click the button and nothing shows. There are 2 errors that do not seem to be linked to anything.

***@***.***

Best regards,

Scott Risoff
Senior ERP Consultant

***@***.***
Direct:  319.739.2941
Fax:  319.294.9003
www.bergankdv.com<http://www.bergankdv.com/>
www.linkedin.com/in/scott-risoff<http://www.linkedin.com/in/scott-risoff>

CONNECT WITH US
[linkedin]<https://www.linkedin.com/company/bergankdv>  [twitter] <https://twitter.com/BerganKDV>   [facebook] <https://www.facebook.com/BerganKDV>   [instagram] <https://instagram.com/bergankdv/>   [youtube] <https://www.youtube.com/channel/UCuA7FKd4TNJ4XqXhikC39Fg>

[O-NetSuite-Cert-SuiteFoundation-horz-rgb]
[MCTS_2013(rgb)_1309]

________________________________
***Caution: this email came from an external source. Please think before clicking on any links or attachments.***

**Comment by burkybang** [comment] 2022-05-12 16:01
I think you still have my meeting link. Can you schedule something with me, so I can check it out?

**Comment by burkybang** [comment] 2022-05-27 19:51
Just some notes to help me keep track of the issue:

@srisoff and I determined this could be an incompatibility issue with the Sticky Notes bundle (49018).

**Comment by burkybang** [comment] 2022-08-05 18:23
I found the issue. The StickyNotes bundle is adding its options to the end of the buttons/actions row in a way that's not really good practice, which removes the click handler from the View button, but I resolved it by implementing the click handler in a different way. The fix will be in the next release, v24.5.3.

**Closed by burkybang** 2022-08-05 18:23 UTC
Labels: bug

**Comment by burkybang** [comment] 2022-08-15 13:58
The update to fix this is out now.
